# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpi_monitor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11mpi_monitor.proto\x12\x0bmpi_monitor\"\x18\n\x07\x44ummy22\x12\r\n\x05mtest\x18\x01 \x01(\t\".\n\x0f\x61\x64\x64itionalNodes\x12\r\n\x05nodes\x18\x01 \x01(\x05\x12\x0c\n\x04mode\x18\x02 \x01(\t\"\x1a\n\x08nodeName\x12\x0e\n\x06nodeIP\x18\x01 \x01(\t\"9\n\x0c\x43onfirmation\x12\x16\n\x0e\x63onfirmMessage\x18\x01 \x01(\t\x12\x11\n\tconfirmId\x18\x02 \x01(\x05\"C\n\x07SSHKeys\x12\x11\n\tpubJobKey\x18\x01 \x01(\t\x12\x12\n\nprivJobKey\x18\x02 \x01(\t\x12\x11\n\tconfirmId\x18\x03 \x01(\x05\x32\x90\x03\n\x07Monitor\x12\x42\n\x05Scale\x12\x1c.mpi_monitor.additionalNodes\x1a\x19.mpi_monitor.Confirmation\"\x00\x12=\n\x0cRetrieveKeys\x12\x15.mpi_monitor.nodeName\x1a\x14.mpi_monitor.SSHKeys\"\x00\x12=\n\x07JobInit\x12\x15.mpi_monitor.nodeName\x1a\x19.mpi_monitor.Confirmation\"\x00\x12\x41\n\x0c\x61\x63tiveServer\x12\x14.mpi_monitor.Dummy22\x1a\x19.mpi_monitor.Confirmation\"\x00\x12\x42\n\rcheckpointing\x12\x14.mpi_monitor.Dummy22\x1a\x19.mpi_monitor.Confirmation\"\x00\x12<\n\x07\x65ndExec\x12\x14.mpi_monitor.Dummy22\x1a\x19.mpi_monitor.Confirmation\"\x00\x42.\n\x13io.grpc.mpi_monitorB\x0fMPIMonitorProtoP\x01\xa2\x02\x03MMGb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mpi_monitor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\023io.grpc.mpi_monitorB\017MPIMonitorProtoP\001\242\002\003MMG'
  _DUMMY22._serialized_start=34
  _DUMMY22._serialized_end=58
  _ADDITIONALNODES._serialized_start=60
  _ADDITIONALNODES._serialized_end=106
  _NODENAME._serialized_start=108
  _NODENAME._serialized_end=134
  _CONFIRMATION._serialized_start=136
  _CONFIRMATION._serialized_end=193
  _SSHKEYS._serialized_start=195
  _SSHKEYS._serialized_end=262
  _MONITOR._serialized_start=265
  _MONITOR._serialized_end=665
# @@protoc_insertion_point(module_scope)
