apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: hypre-job
spec:
  minAvailable: 4
  schedulerName: volcano
  plugins:
    ssh: []
    svc: []
  tasks:
    - replicas: 1
      name: mpimaster
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        spec:
          containers:
            - command:
                - /bin/bash 
                - -c
                - |
                  MPI_HOST=`cat /etc/volcano/mpiworker.host | tr "\n" ","`;
                  mkdir -p /var/run/sshd; /usr/sbin/sshd;
                  time mpiexec --allow-run-as-root -x OMP_NUM_THREADS=8 --host ${MPI_HOST} -np 3 ./ex13 -n 3500;
              image: raijenki/mpik8s:hyprearm
              imagePullPolicy: Always
              name: mpimaster
              ports:
                - containerPort: 22
                  name: mpijob-port
              workingDir: /home
          restartPolicy: OnFailure
    - replicas: 3
      name: mpiworker
      template:
        metadata:
          labels:
            mpitype: worker
        spec:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: zone
              whenUnsatisfiable: ScheduleAnyway
              labelSelector:
                matchLabels:
                  mpitype: worker
          containers:
            - command:
                - /bin/sh
                - -c
                - |
                  mkdir -p /var/run/sshd; /usr/sbin/sshd -D;
              image: raijenki/mpik8s:hyprearm
              imagePullPolicy: Always
              name: mpiworker
              resources:
                requests:
                  cpu: "6000m"
              ports:
                - containerPort: 22
                  name: mpijob-port
              workingDir: /home
          restartPolicy: OnFailure