apiVersion: batch/v1
kind: Job
metadata:
  name: sched
spec:
  manualSelector: true
  selector:
    matchLabels:
      app: sched
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: sched
    spec:
      serviceAccountName: scaler-dft
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
      - name: stream
        image: raijenki/mpik8s:smpi
        imagePullPolicy: Always
          #command: ["/bin/sleep", "7200"]
        volumeMounts:
          - mountPath: /data
            name: task-pv-storage
        command: ["/usr/bin/python3", "hpc-tests/stream-mpi/scheduler.py"]
        args: ["4"]
      restartPolicy: Never
